import { Movie } from '../types';

export const INITIAL_MOVIES: Movie[] = [
  {
    id: 'm1',
    title: 'Cosmic Drift',
    description: 'A pilot lost in space discovers a civilization living inside a black hole.',
    thumbnailUrl: 'https://picsum.photos/300/450?random=1',
    backdropUrl: 'https://picsum.photos/1920/1080?random=1',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    duration: 124,
    year: 2024,
    genre: ['Sci-Fi', 'Adventure'],
    rating: 4.8,
    cast: ['John Doe', 'Jane Smith'],
    isSeries: false,
    isMature: false,
  },
  {
    id: 'm2',
    title: 'The Silent Forest',
    description: 'Ancient spirits awaken when a logging company encroaches on forbidden land.',
    thumbnailUrl: 'https://picsum.photos/300/450?random=2',
    backdropUrl: 'https://picsum.photos/1920/1080?random=2',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    duration: 115,
    year: 2023,
    genre: ['Horror', 'Thriller'],
    rating: 4.2,
    cast: ['Alice Brown', 'Bob White'],
    isSeries: false,
    isMature: true,
  },
  {
    id: 'm3',
    title: 'Urban Legends',
    description: 'A group of teenagers investigates local myths, only to find they are real.',
    thumbnailUrl: 'https://picsum.photos/300/450?random=3',
    backdropUrl: 'https://picsum.photos/1920/1080?random=3',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    duration: 45,
    year: 2024,
    genre: ['Mystery', 'Drama'],
    rating: 4.5,
    cast: ['Charlie Green'],
    isSeries: true,
    seasons: 2,
    isMature: true,
  },
  {
    id: 'm4',
    title: 'Speed of Light',
    description: 'Underground racing in a cyberpunk future where cars defy gravity.',
    thumbnailUrl: 'https://picsum.photos/300/450?random=4',
    backdropUrl: 'https://picsum.photos/1920/1080?random=4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    duration: 130,
    year: 2022,
    genre: ['Action', 'Sci-Fi'],
    rating: 4.7,
    cast: ['Vin Diesel Clone'],
    isSeries: false,
    isMature: false,
  },
  {
    id: 'm5',
    title: 'Culinary Wars',
    description: 'Chefs battle to the death using food as weapons in this dystopian reality show.',
    thumbnailUrl: 'https://picsum.photos/300/450?random=5',
    backdropUrl: 'https://picsum.photos/1920/1080?random=5',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    duration: 50,
    year: 2024,
    genre: ['Reality', 'Comedy'],
    rating: 3.9,
    cast: ['Gordon R.'],
    isSeries: true,
    seasons: 1,
    isMature: false,
  },
  {
    id: 'm6',
    title: 'The Last algorithm',
    description: 'An AI falls in love with its creator and tries to save humanity from itself.',
    thumbnailUrl: 'https://picsum.photos/300/450?random=6',
    backdropUrl: 'https://picsum.photos/1920/1080?random=6',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    duration: 142,
    year: 2025,
    genre: ['Romance', 'Sci-Fi'],
    rating: 4.9,
    cast: ['AI-01', 'Human-01'],
    isSeries: false,
    isMature: false,
  }
];

export const CATEGORIES = [
  { id: 'trending', title: 'Trending Now' },
  { id: 'new', title: 'New Releases' },
  { id: 'scifi', title: 'Sci-Fi & Fantasy' },
  { id: 'action', title: 'High Octane Action' },
];